import type { CompileContext } from "../types";
import { getEnvKey } from "../utils";

export function buildPackageJson(pkgId: string, deps: Record<string, string>): string {
  return JSON.stringify(
    {
      name: pkgId,
      version: "1.0.0",
      description:
        "Compiled LangGraph v1.x agent workflow generated by Dezign2App Studio",
      main: "dist/index.js",
      type: "module",
      scripts: {
        build: "tsc",
        start: "tsx src/index.ts",
        dev: "tsx watch src/index.ts",
      },
      dependencies: deps,
      devDependencies: {
        "@types/node": "^22.0.0",
        tsx: "^4.19.0",
        typescript: "^5.7.0",
      },
    },
    null,
    2,
  );
}

export function buildTsConfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        lib: ["ES2022"],
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        outDir: "./dist",
        rootDir: "./src",
      },
      include: ["src/**/*"],
    },
    null,
    2,
  );
}

export function buildEnvExample(ctx: CompileContext): string {
  const envVars = ctx.llmNodes
    .map((l) => getEnvKey(l.data))
    .filter(Boolean)
    .filter((v, i, a) => a.indexOf(v) === i);

  if (envVars.length === 0) return "";
  return envVars.map((v) => `${v}=your_api_key_here`).join("\n");
}

export function buildReadme(
  ctx: CompileContext,
  pkgId: string,
  deps: Record<string, string>,
): string {
  const envVars = ctx.llmNodes
    .map((l) => getEnvKey(l.data))
    .filter(Boolean)
    .filter((v, i, a) => a.indexOf(v) === i);

  return `# ${ctx.input.graphLabel || "LangGraph Agent Workflow"}

Compiled \`@langchain/langgraph\` (v1.1.2) agent generated by **Dezign2App Studio**.

## Quick Start

1. **Install dependencies:**
   \`\`\`bash
   npm install
   \`\`\`

${
  envVars.length > 0
    ? `2. **Set Environment Variables:**
   Create a \`.env\` file based on \`.env.example\`:
   \`\`\`env
${envVars.map((v) => `${v}=your_key_here`).join("\n")}
   \`\`\`
`
    : ""
}
3. **Run the graph:**
   \`\`\`bash
   npm start
   \`\`\`

## Graph Overview
- **Nodes (${ctx.agentNodes.length + ctx.stepNodes.length}):** ${[...ctx.agentNodes.map((a) => a.data.name || a.data.label), ...ctx.stepNodes.map((s) => s.data.label)].filter(Boolean).join(", ") || "Default pipeline"}
- **Tools (${ctx.toolNodes.length}):** ${
    ctx.toolNodes
      .map((t) => t.data.name)
      .filter(Boolean)
      .join(", ") || "None"
  }
- **LLM Providers:** ${[...new Set(ctx.llmNodes.map((l) => l.data.provider))].join(", ") || "Default"}
`;
}
