import type { DatabaseEngine } from "../techStack";
import type {
  RedisDataStructure,
  RedisDuration,
  CacheStrategy,
  SerializationFormat,
  CompressionFormat,
  RedisHashField,
  RedisGeoConfig,
  RedisBitfieldConfig,
  RedisStreamConfig,
  RedisListConfig,
  RedisSetConfig,
  RedisZSetConfig,
  RedisBitmapConfig,
  RedisHyperLogLogConfig,
  RedisJsonConfig,
} from "./redis";

/** Database operation function (CRUD, index fetch, or custom query) */
export interface DbOperationFunction {
  id: string;
  name: string;
  kind: "findAll" | "findById" | "create" | "update" | "delete" | "fetchByIndex" | "join" | "custom";
  description?: string;
  signature?: string;
  indexName?: string;
  params?: { name: string; type: string; required?: boolean; defaultValue?: string }[];
  returnType?: string;
  returnTypeMode?: "fixed" | "inferred";
  query?: string;
  pagination?: {
    enabled?: boolean;
    defaultLimit?: number;
    maxLimit?: number;
    mode?: "offset" | "cursor";
  };
  logicMode?: "natural_language" | "code";
  prompt?: string;
  code?: string;
  enabled?: boolean;
  isAutoGenerated?: boolean;
  testCases?: DbOperationTestCase[];
  connectedDbIds?: string[];
  connectedTableNames?: string[];
}

export interface DbOperationTestCase {
  id: string;
  name: string;
  params: Record<string, unknown>;
  expectedOutput?: unknown;
  lastResult?: {
    success: boolean;
    output?: unknown;
    error?: string;
    durationMs?: number;
    executedAt?: string;
    rawCommand?: string;
  };
}

export interface CanvasEntityColumn {
  name: string;
  type: string;
  isPrimaryKey?: boolean;
  isPrimary?: boolean;
  primaryKey?: boolean;
  isForeignKey?: boolean;
  isNotNull?: boolean;
  isUnique?: boolean;
  references?: { table: string; column: string };
  enumValues?: string[];
  options?: string[];
  defaultValue?: string;
  description?: string;
  required?: boolean;
}

export type EntityColumn = CanvasEntityColumn;

/** Database entity / table schema fields (canvas type). */
export interface CanvasEntityNodeData {
  tableName?: string;
  isSchemaGroup?: boolean;
  variant?: string;
  dbType?: "relational" | "document" | "vector" | "redis" | "key-value";
  /** Column definitions stored as part of the node. */
  columns?: CanvasEntityColumn[];
  indexes?: {
    name: string;
    columns: string;
    isUnique?: boolean;
  }[];
  /** DB Operation functions (CRUD, index queries, custom queries). */
  dbOperations?: DbOperationFunction[];
  /** For vector DB entities. */
  embeddingModel?: string;
  dimensions?: number;
  metric?: "Cosine" | "Dot Product" | "Euclidean";
  /** For Redis schema entities. */
  redisDataStructure?: RedisDataStructure;
  redisVersion?: string;
  keyTemplate?: string;
  clusterHashTagParam?: string;
  ttl?: RedisDuration;
  cacheStrategy?: CacheStrategy;
  negativeCaching?: {
    enabled: boolean;
    ttl?: RedisDuration;
  };
  staleWhileRevalidate?: {
    enabled: boolean;
    refreshInterval?: RedisDuration;
  };
  sourceOfTruth?: {
    tableNodeId?: string;
    tableName?: string;
  };
  invalidationRules?: string;
  serialization?: SerializationFormat;
  compression?: CompressionFormat;
  hashConfig?: {
    fields: RedisHashField[];
  };
  geoConfig?: RedisGeoConfig;
  bitfieldConfig?: RedisBitfieldConfig;
  streamConfig?: RedisStreamConfig;
  listConfig?: RedisListConfig;
  setConfig?: RedisSetConfig;
  zsetConfig?: RedisZSetConfig;
  bitmapConfig?: RedisBitmapConfig;
  hyperloglogConfig?: RedisHyperLogLogConfig;
  jsonConfig?: RedisJsonConfig;
  isNestedJsonSchema?: boolean;
  rawJsonSchema?: string;
  jsonRootType?: "object" | "array";
  /** Reference to entity node ID (used by DB Ref nodes). */
  tableRef?: string;
  /** Reference to vector collection (used by Vector DB Ref nodes). */
  collectionRef?: string;
  /** Reference to Redis schema node (used by Redis Cache Ref nodes). */
  schemaRef?: string;
  /** Reference to DB node (used by Vector DB Ref nodes or Entity nodes). */
  dbRef?: string;
  /** Associated Database node ID to which this table hangs. */
  databaseId?: string;
  /** Seed data rows for the entity. */
  seedRows?: Record<string, string | number | boolean | null>[];
}

export interface DatabaseTableDefinition {
  id?: string;
  name?: string;
  label?: string;
  tableRef?: string;
  columns?: Array<{
    name?: string;
    type?: string;
    isPrimaryKey?: boolean;
    isPrimary?: boolean;
    primaryKey?: boolean;
    isNotNull?: boolean;
    required?: boolean;
  }>;
  fields?: Array<{
    name?: string;
    type?: string;
    isPrimaryKey?: boolean;
    isPrimary?: boolean;
    primaryKey?: boolean;
    isNotNull?: boolean;
    required?: boolean;
  }>;
}

/** Database node fields — connection configurations, environment variables, engine. */
export interface CanvasDatabaseNodeData {
  tables?: DatabaseTableDefinition[];
  dbEngine?: DatabaseEngine | string;
  dbType?: "relational" | "document" | "vector" | "redis" | "key-value" | "nosql";
  dbCategory?: "sql" | "nosql" | "vector" | "key-value";
  provider?: string;
  dbConnectionType?: "env_var" | "connection_string";
  connectionString?: string;
  connectionStringEnv?: string;
  dbFilePath?: string;
  dbFilePathEnv?: string;
  hostEnv?: string;
  portEnv?: string;
  host?: string;
  port?: string | number;
  database?: string;
  user?: string;
  username?: string;
  password?: string;
  databaseNameEnv?: string;
  usernameEnv?: string;
  passwordEnv?: string;
  apiKeyEnv?: string;
  isDefault?: boolean;
  // Redis instance-wide server configurations
  maxmemoryPolicy?:
    | "noeviction"
    | "allkeys-lru"
    | "volatile-lru"
    | "allkeys-lfu"
    | "volatile-lfu"
    | "volatile-ttl"
    | "allkeys-random"
    | "volatile-random";
  maxmemory?: string;
  persistenceMode?: "RDB" | "AOF" | "RDB+AOF" | "None";
  clustering?: boolean;
  redisVersion?: string;
  lastConnectionStatus?: {
    connected: boolean;
    latencyMs?: number;
    checkedAt?: string;
    serverInfo?: Record<string, unknown>;
    error?: string;
  };
  /** Env vars declared on this DB node — merged into any consuming app's .env at compile time. */
  envVars?: Array<{ id: string; name: string; description?: string }>;
}
