import type { JSONValue } from "./canvas-core";
import type { BackendNodeType, BackendNode } from "./nodes";
import type { BackendEdgeType, BackendEdge } from "./edges";


export type Parameter = {
  id: string;
  name: string;
  type: string;
  required: boolean;
  description?: string;
  defaultValue?: string;
  key?: string;
  value?: string;
  enabled?: boolean;
  enumValues?: string[];
  isArray?: boolean;
};

export type Schema = {
  id: string;
  fields?: Parameter[];
  rawJson?: string;
  mode?: "field_builder" | "raw_json";
  requestBodyMode?: "field_builder" | "raw_json";
};

import type { processingOperationEnum, parameterTypeEnum } from "../schemas/primitives";
import type { z } from "zod";

export type ProcessingOperation = z.infer<typeof processingOperationEnum>;
export type ParameterType = z.infer<typeof parameterTypeEnum>;



// UI Specific Types
export type StateVariableType = "string" | "number" | "boolean" | "array" | "object";

export interface SectionStateVariable {
  id: string;
  name: string;
  type: StateVariableType;
  defaultValue?: JSONValue;
  description?: string;
}

export type PageSection = {
  id: string;
  name: string;
  renderMode?: "server" | "client";
  loadStrategy?: "eager" | "dynamic" | "dynamic-no-ssr";
  actions: UIEventItem[];
  states?: SectionStateVariable[];
  description?: string;
  uiPrompt?: string;
  libraries?: string[];
  images?: string[];
  primaryImageUrl?: string;
};

export type UIEventItem = {
  id: string;
  name: string;
  event?: string;
  schema?: string;
  headers?: Parameter[];
  pathParams?: Parameter[];
  queryParams?: Parameter[];
  requestBody?: Schema;
  requestBodyMode?: "field_builder" | "raw_json";
  navigationType?: "link" | "router";
  navigationCondition?: "direct" | "on_success" | "on_condition" | "on_error";
  targetRoute?: string;
  targetPageId?: string;
  conditionCode?: string;
  testCases?: SimulationTestCase[];
  // AI context
  description?: string;
  uiPrompt?: string;
  libraries?: string[];
  renderMode?: "server" | "client";
  // State Store action binding
  storeActionBinding?: {
    storeNodeId?: string;
    storeName?: string;
    actionId?: string;
    actionName?: string;
    actionType?: "set" | "append" | "remove" | "toggle" | "custom";
  };
  // SSE config (when event === "sse")
  sseConfig?: {
    reconnectStrategy?: "none" | "exponential" | "linear";
    maxRetries?: number;
    retryDelay?: number;
    eventTypes?: string[];
    withCredentials?: boolean;
    authMode?: "header" | "query" | "cookie" | "none";
  };
  // WebSocket config (when event === "websocket")
  wsConfig?: {
    protocol?: "json" | "binary" | "text";
    reconnectOnDisconnect?: boolean;
    heartbeatInterval?: number;
    authMode?: "query-param" | "header" | "first-message" | "none";
    messageHandlers?: { name: string; description: string }[];
  };
  // WebRTC config (when event === "webrtc")
  webRtcConfig?: {
    signalingServer?: string;
    iceServers?: {
      urls: string;
      username?: string;
      credential?: string;
    }[];
    mediaConstraints?: { audio: boolean; video: boolean };
    hasDataChannel?: boolean;
    role?: "initiator" | "responder" | "both";
    description?: string;
  };
  // Polling config (when event === "polling")
  pollingConfig?: {
    intervalMs?: number;
    stopOnError?: boolean;
    maxRounds?: number;
  };
};

/** A global simulation scenario. */
export type SimulationTestCase = {
  id: string;
  name: string;
  targetNodeId: string;
  targetEventId?: string;
  isAutoGenerated?: boolean;
  category?: "auto" | "manual";
  /** Incoming route/edge that invokes a LangGraph node. */
  targetRouteId?: string;
  /** Initial values for LangGraph state channels before the graph starts. */
  initialState?: Record<string, JSONValue>;
  /** Explicit branch choice for each router step, keyed by router step id. */
  routerChoices?: Record<string, string>;
  /** Expected final LangGraph state values. */
  expectedState?: Record<string, JSONValue>;
  request?: {
    headers?: Record<string, string>;
    params?: Record<string, string>;
    body?: JSONValue;
  };
  expectedStatus?: number;
  expectedBody?: JSONValue;
  enabled?: boolean;
  mocks?: Record<string, { returnData?: JSONValue; status?: number }>;
  expectedPath?: string[];
};

export interface TestCaseItem {
  id?: string;
  testCaseId?: string;
  name?: string;
  targetNodeId?: string;
  nodeId?: string;
  targetEventId?: string;
  request?: {
    headers?: Record<string, string>;
    params?: Record<string, string>;
    body?: JSONValue;
  };
  expectedStatus?: number;
  expectedBody?: JSONValue;
}

// --- AI Adapter Types ---

export type CanvasOperation =
  | {
      op: "add_node";
      type: BackendNodeType;
      label: string;
      position?: { x: number; y: number };
      data?: Partial<BackendNode["data"]>;
    }
  | { op: "update_node"; id: string; changes: Partial<BackendNode> }
  | { op: "delete_node"; id: string }
  | {
      op: "add_edge";
      source: string;
      target: string;
      type: BackendEdgeType;
      data?: Partial<BackendEdge["data"]>;
    }
  | { op: "update_edge"; id: string; changes: Partial<BackendEdge> }
  | { op: "delete_edge"; id: string }
  | { op: "run_auto_layout" }
  | {
      op: "add_shape";
      type: string;
      x: number;
      y: number;
      props: Record<string, string | number | boolean | null>;
    }
  | {
      op: "update_shape";
      id: string;
      props: Record<string, string | number | boolean | null>;
    }
  | { op: "delete_shape"; id: string };

export interface CanvasAdapter<TDoc> {
  getState: () => TDoc;
  applyOperations: (ops: CanvasOperation[]) => void;
  serialize: () => string; // For AI context
}

// --- Input Types (for AI tools & Store operations) ---

export interface ParameterInputType {
  id?: string;
  name: string;
  type: string;
  required: boolean;
  description?: string;
  defaultValue?: string;
  key?: string;
  value?: string;
}

export interface PublishedEventInputType {
  id?: string;
  name: string;
  kind?: string;
  schema?: string;
  targetNodeId?: string;
  targetResourceId?: string;
}

export interface ConsumedEventInputType {
  id?: string;
  name: string;
  kind?: string;
  schema?: string;
  handlerLogic?: string;
  targetNodeId?: string;
  targetResourceId?: string;
}

export interface EndpointInputType {
  id?: string;
  name: string;
  type: string;
  headers?: ParameterInputType[];
  pathParams?: ParameterInputType[];
  queryParams?: ParameterInputType[];
  requestBody?: { fields: ParameterInputType[]; rawJson?: string };
  responseBody?: { fields: ParameterInputType[]; rawJson?: string };
  simulationOutput?: JSONValue;
  processingSteps?: {
    id?: string;
    text: string;
    operation?: string;
    config?: Record<string, string | number | boolean | null>;
  }[];
  output?: string;
  businessLogic?: string;
  summary?: string;
  requiredRoles?: string[];
  requiredScopes?: string[];
  audience?: string;
  databaseNodeIds?: string[];
  databaseNodeId?: string;
  publishedEvents?: PublishedEventInputType[];
  requestBodyMode?: "field_builder" | "raw_json";
  responseMode?: "field_builder" | "raw_json" | "custom_expression" | "schema_builder" | "inferred";
  responseExpression?: string;
  requireAuth?: boolean;
  code?: string;
  /** Ordered pipeline steps — explicit field-level bindings per argument */
  pipelineSteps?: EndpointPipelineStepInput[];
}

import type { PipelineStepDraft } from "./pipeline";

export type EndpointPipelineStepInput = PipelineStepDraft;

