// ---------------------------------------------------------------------------
// Step Identification & Condition Summary Helpers
// ---------------------------------------------------------------------------

export function isAutoGeneratedStepName(name?: string): boolean {
  if (!name || !name.trim()) return true;
  return /^(condition|tryCatch|switch|parallel|loop|earlyReturn|transformedData|dbResult|cachedResult|publishResult|serviceResponse|externalResult|agentResult|step)\d+(Result|Results)?$/i.test(
    name.trim(),
  );
}

export function formatSourceShort(source?: any): string {
  if (!source) return "";
  if (source.kind === "inline") {
    if (typeof source.value === "string") {
      return /\$\{([^}]+)\}/.test(source.value) ? `\`${source.value}\`` : `"${source.value}"`;
    }
    return String(source.value ?? "");
  }
  const prefix =
    source.kind === "req_body"
      ? "body"
      : source.kind === "req_params"
      ? "params"
      : source.kind === "req_query"
      ? "query"
      : source.kind === "req_headers"
      ? "headers"
      : source.kind === "step_output"
      ? "step"
      : "";
  if ("field" in source && source.field && source.field.trim()) {
    return prefix ? `${prefix}.${source.field.trim()}` : source.field.trim();
  }
  return "";
}

export function formatConditionSummary(expr?: any): string {
  if (!expr) return "condition";
  if ("left" in expr && "operator" in expr) {
    const leftStr = formatSourceShort(expr.left);
    if (!leftStr) return "condition";
    const op = expr.operator;
    if (op === "truthy") return leftStr;
    if (op === "falsy") return `!${leftStr}`;
    if (op === "is_null") return `${leftStr} == null`;
    if (op === "is_not_null") return `${leftStr} != null`;
    const rightStr = formatSourceShort(expr.right);
    if (!rightStr) return leftStr;
    const opMap: Record<string, string> = {
      eq: "==",
      neq: "!=",
      gt: ">",
      gte: ">=",
      lt: "<",
      lte: "<=",
      contains: ".includes",
      in: "in",
    };
    const symbol = opMap[op] || op;
    return `${leftStr} ${symbol} ${rightStr}`.trim();
  }
  return "condition";
}
