"use client";

import React, { useState, useRef, useCallback } from "react";
import { Endpoint, BackendNode, BackendEdge, AnyMessagingResource } from "@workspace/canvas/types";
import { useBufferedInput } from "@/lib/hooks/useBufferedInput";
import { Input } from "@workspace/ui/components/input";
import { Label } from "@workspace/ui/components/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@workspace/ui/components/select";
import { Check, AlertTriangle } from "lucide-react";
import { Draggable } from "@hello-pangea/dnd";
import { StepRowHeader } from "./StepRowHeader";
import { TransformerStepSection } from "./TransformerStepSection";
import { DbOperationStepSection } from "./DbOperationStepSection";
import { RedisOperationStepSection } from "./RedisOperationStepSection";
import { KafkaPublishStepSection } from "./KafkaPublishStepSection";
import { ServiceCallStepSection } from "./ServiceCallStepSection";
import { ExternalCallStepSection } from "./ExternalCallStepSection";
import { GenericFunctionRefSection } from "./GenericFunctionRefSection";
import { CustomCodeSection } from "./CustomCodeSection";
import { ArgumentBindingsSection } from "./ArgumentBindingsSection";
import { ConditionStepSection } from "./ConditionStepSection";
import { TryCatchStepSection } from "./TryCatchStepSection";
import { SwitchStepSection } from "./SwitchStepSection";
import { ParallelStepSection } from "./ParallelStepSection";
import { LoopStepSection } from "./LoopStepSection";
import { EarlyReturnStepSection } from "./EarlyReturnStepSection";
import { ConditionExprEditor } from "./ConditionExprEditor";
import { useStepRowState } from "./useStepRowState";
import { StepType, PipelineStepDraft, AvailableSource } from "./types";
import { STEP_TYPE_META, ADDABLE_STEP_TYPES, isAutoGeneratedStepName } from "./utils";
import { PushToClientStepSection } from "./PushToClientStepSection";
import { StepOnErrorSection } from "./StepOnErrorSection";
import { LangGraphInvokeStepSection } from "./LangGraphInvokeStepSection";

const HAS_OUTPUT_VAR_TYPES = new Set<StepType>([
  "transform",
  "db_operation",
  "redis_operation",
  "kafka_publish",
  "service_call",
  "external_call",
  "custom_code",
]);

function isStepType(val: string): val is StepType {
  return val in STEP_TYPE_META;
}

export interface StepRowProps {
  step: PipelineStepDraft;
  index: number;
  priorSteps: PipelineStepDraft[];
  endpoint?: Endpoint;
  consumedEvent?: AnyMessagingResource;
  allNodes: BackendNode[];
  allEdges: BackendEdge[];
  serviceNodeId?: string;
  depth?: number;
  extraSources?: AvailableSource[];
  onChange: (updated: PipelineStepDraft) => void;
  onDelete: () => void;
  isFirst: boolean;
  isLast: boolean;
  onMoveUp: () => void;
  onMoveDown: () => void;
}

export const StepRow = ({
  step,
  index,
  priorSteps,
  endpoint,
  consumedEvent,
  allNodes,
  allEdges,
  serviceNodeId,
  depth = 0,
  extraSources = [],
  onChange,
  onDelete,
  isFirst,
  isLast,
  onMoveUp,
  onMoveDown,
}: StepRowProps) => {
  const [expanded, setExpanded] = useState(false);
  const [showAdvancedSettings, setShowAdvancedSettings] = useState(false);
  const [showRunIfGuard, setShowRunIfGuard] = useState(Boolean(step.runIf));

  const stepRef = useRef(step);
  stepRef.current = step;
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;

  const stepNameBuffer = useBufferedInput(
    isAutoGeneratedStepName(step.name) ? "" : (step.name ?? ""),
    useCallback((val: string) => {
      onChangeRef.current({ ...stepRef.current, name: val });
    }, []),
    150,
  );

  const descBuffer = useBufferedInput(
    step.description ?? "",
    useCallback((val: string) => {
      onChangeRef.current({ ...stepRef.current, description: val });
    }, []),
    150,
  );

  const outputVarBuffer = useBufferedInput(
    step.outputVariable ?? "",
    useCallback((val: string) => {
      onChangeRef.current({
        ...stepRef.current,
        outputVariable: val,
        name: isAutoGeneratedStepName(stepRef.current.name) ? val : stepRef.current.name,
      });
    }, []),
    150,
  );

  const {
    meta,
    availableSources,
    availableTransformers,
    selectedDbId,
    expectedArgs,
    isUnconfigured,
    stepId,
    displayVarName,
    handleAutoMapArguments,
    updateBinding,
    addBinding,
    removeBinding,
  } = useStepRowState({
    step,
    index,
    priorSteps,
    endpoint,
    consumedEvent,
    allNodes,
    allEdges,
    serviceNodeId,
    extraSources,
    onChange,
  });

  return (
    <Draggable draggableId={stepId} index={index}>
      {(provided, snapshot) => (
        <div
          ref={provided.innerRef}
          {...provided.draggableProps}
          className={`rounded-lg border transition-all duration-150 ${
            step.enabled === false ? "opacity-50" : ""
          } ${
            snapshot.isDragging
              ? "border-primary shadow-xl shadow-black/25 bg-background z-50 ring-1 ring-primary/40"
              : "border-border/60 bg-card/40 hover:border-border/80"
          }`}
        >
          {/* Header */}
          <StepRowHeader
            step={step}
            index={index}
            meta={meta}
            displayVarName={displayVarName}
            isUnconfigured={isUnconfigured}
            expanded={expanded}
            isFirst={isFirst}
            isLast={isLast}
            dragHandleProps={provided.dragHandleProps}
            onToggleExpand={() => setExpanded((v) => !v)}
            onMoveUp={onMoveUp}
            onMoveDown={onMoveDown}
            onDelete={onDelete}
            onChange={onChange}
          />

          {/* Expanded Step Body */}
          {expanded && (
            <div className="border-t border-border/40 px-3 pt-3 pb-3 flex flex-col gap-3.5">
              {/* Unconfigured Warning Banner */}
              {isUnconfigured && (
                <div className="flex items-center gap-2 px-2.5 py-1.5 rounded-md border border-destructive/40 bg-destructive/10 text-destructive text-[11px]">
                  <AlertTriangle size={12} className="shrink-0" />
                  <span>Input variables for this step are not configured. Map the arguments below.</span>
                </div>
              )}

              {/* Step Identification & Type */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                <div className="flex flex-col gap-1">
                  <Label className="text-[10px] text-muted-foreground font-medium">
                    Step Name / Title
                  </Label>
                  <Input
                    className="h-7 text-xs bg-background/60 border-border/60"
                    value={stepNameBuffer.value}
                    onChange={(e) => stepNameBuffer.onChange(e.target.value)}
                    onBlur={stepNameBuffer.flush}
                    placeholder={
                      step.type === "condition"
                        ? "e.g. Check active user session"
                        : step.type === "db_operation"
                        ? "e.g. Create Conversation"
                        : "e.g. Step name..."
                    }
                  />
                </div>
                <div className="flex flex-col gap-1">
                  <Label className="text-[10px] text-muted-foreground font-medium">Step Type</Label>
                  <Select
                    value={step.type}
                    onValueChange={(v) => {
                      if (!isStepType(v)) return;
                      const nextVar =
                        v === "transform"
                          ? `transformedData${index + 1}`
                          : v === "db_operation"
                          ? `dbResult${index + 1}`
                          : v === "redis_operation"
                          ? `cachedResult${index + 1}`
                          : v === "kafka_publish"
                          ? `publishResult${index + 1}`
                          : v === "service_call"
                          ? `serviceResponse${index + 1}`
                          : v === "external_call"
                          ? `externalResult${index + 1}`
                          : v === "condition"
                          ? `condition${index + 1}Result`
                          : v === "try_catch"
                          ? `tryCatch${index + 1}Result`
                          : v === "switch"
                          ? `switch${index + 1}Result`
                          : v === "parallel"
                          ? `parallel${index + 1}Results`
                          : v === "loop"
                          ? `loop${index + 1}Results`
                          : v === "early_return"
                          ? `earlyReturn${index + 1}`
                          : v === "langgraph_invoke"
                          ? `agentResult${index + 1}`
                          : `step${index + 1}Result`;
                      onChange({
                        ...step,
                        type: v,
                        outputVariable: step.outputVariable || nextVar,
                        name: isAutoGeneratedStepName(step.name) ? nextVar : step.name,
                      });
                    }}
                  >
                    <SelectTrigger className="h-7 text-xs bg-background/60 border-border/60">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {ADDABLE_STEP_TYPES
                        .filter((t) => Boolean(t && t.trim()))
                        .map((t) => (
                          <SelectItem key={t} value={t}>
                            {STEP_TYPE_META[t].label}
                          </SelectItem>
                        ))}
                    </SelectContent>
                  </Select>
                </div>
              </div>

              {/* Description and (if applicable) Output Variable */}
              <div
                className={`grid ${
                  HAS_OUTPUT_VAR_TYPES.has(step.type) ? "grid-cols-1 sm:grid-cols-2" : "grid-cols-1"
                } gap-2`}
              >
                <div className="flex flex-col gap-1">
                  <Label className="text-[10px] text-muted-foreground font-medium">
                    Description <span className="text-muted-foreground/50 font-normal">(optional)</span>
                  </Label>
                  <Input
                    className="h-7 text-xs bg-background/60 border-border/60"
                    value={descBuffer.value}
                    onChange={(e) => descBuffer.onChange(e.target.value)}
                    onBlur={descBuffer.flush}
                    placeholder="Add description..."
                  />
                </div>
                {HAS_OUTPUT_VAR_TYPES.has(step.type) && (
                  <div className="flex flex-col gap-1">
                    <Label className="text-[10px] text-muted-foreground font-medium">
                      Output Variable Name
                    </Label>
                    <Input
                      className="h-7 text-xs font-mono bg-background/60 border-border/60"
                      value={outputVarBuffer.value}
                      onChange={(e) => outputVarBuffer.onChange(e.target.value)}
                      onBlur={outputVarBuffer.flush}
                      placeholder="e.g. createdProduct"
                    />
                  </div>
                )}
              </div>

              {/* Step Type Specific Sections */}
              {(() => {
                const argumentBindingsSection = (
                  <ArgumentBindingsSection
                    bindings={step.inputBindings || []}
                    expectedArgs={expectedArgs}
                    availableSources={availableSources}
                    onAddBinding={addBinding}
                    onUpdateBinding={updateBinding}
                    onRemoveBinding={removeBinding}
                    onAutoMapArguments={handleAutoMapArguments}
                  />
                );

                if (step.type === "condition") {
                  return (
                    <ConditionStepSection
                      step={step}
                      availableSources={availableSources}
                      endpoint={endpoint}
                      consumedEvent={consumedEvent}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      depth={depth}
                      onChange={onChange}
                    />
                  );
                }

                if (step.type === "try_catch") {
                  return (
                    <TryCatchStepSection
                      step={step}
                      availableSources={availableSources}
                      endpoint={endpoint}
                      consumedEvent={consumedEvent}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      depth={depth}
                      onChange={onChange}
                    />
                  );
                }

                if (step.type === "switch") {
                  return (
                    <SwitchStepSection
                      step={step}
                      availableSources={availableSources}
                      endpoint={endpoint}
                      consumedEvent={consumedEvent}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      depth={depth}
                      onChange={onChange}
                    />
                  );
                }

                if (step.type === "parallel") {
                  return (
                    <ParallelStepSection
                      step={step}
                      availableSources={availableSources}
                      endpoint={endpoint}
                      consumedEvent={consumedEvent}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      depth={depth}
                      onChange={onChange}
                    />
                  );
                }

                if (step.type === "loop") {
                  return (
                    <LoopStepSection
                      step={step}
                      availableSources={availableSources}
                      endpoint={endpoint}
                      consumedEvent={consumedEvent}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      depth={depth}
                      onChange={onChange}
                    />
                  );
                }

                if (step.type === "early_return") {
                  return (
                    <EarlyReturnStepSection
                      step={step}
                      availableSources={availableSources}
                      expectedArgs={expectedArgs}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    />
                  );
                }

                if (step.type === "transform") {
                  return (
                    <TransformerStepSection
                      step={step}
                      availableTransformers={availableTransformers}
                      serviceNodeId={serviceNodeId}
                      endpointId={endpoint?.id}
                      expectedArgs={expectedArgs}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    >
                      {argumentBindingsSection}
                    </TransformerStepSection>
                  );
                }

                if (step.type === "db_operation") {
                  return (
                    <DbOperationStepSection
                      step={step}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      expectedArgs={expectedArgs}
                      selectedDbId={selectedDbId}
                      showAdvancedSettings={showAdvancedSettings}
                      onToggleAdvancedSettings={() => setShowAdvancedSettings((v) => !v)}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    >
                      {argumentBindingsSection}
                    </DbOperationStepSection>
                  );
                }

                if (step.type === "redis_operation") {
                  return (
                    <RedisOperationStepSection
                      step={step}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      expectedArgs={expectedArgs}
                      selectedDbId={selectedDbId}
                      serviceNodeId={serviceNodeId}
                      endpointId={endpoint?.id}
                      consumedEventId={consumedEvent?.id}
                      showAdvancedSettings={showAdvancedSettings}
                      onToggleAdvancedSettings={() => setShowAdvancedSettings((v) => !v)}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    >
                      {argumentBindingsSection}
                    </RedisOperationStepSection>
                  );
                }

                if (step.type === "kafka_publish") {
                  return (
                    <KafkaPublishStepSection
                      step={step}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      expectedArgs={expectedArgs}
                      showAdvancedSettings={showAdvancedSettings}
                      onToggleAdvancedSettings={() => setShowAdvancedSettings((v) => !v)}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    >
                      {argumentBindingsSection}
                    </KafkaPublishStepSection>
                  );
                }

                if (step.type === "service_call") {
                  return (
                    <ServiceCallStepSection
                      step={step}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      expectedArgs={expectedArgs}
                      showAdvancedSettings={showAdvancedSettings}
                      onToggleAdvancedSettings={() => setShowAdvancedSettings((v) => !v)}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    >
                      {argumentBindingsSection}
                    </ServiceCallStepSection>
                  );
                }

                if (step.type === "external_call") {
                  return (
                    <ExternalCallStepSection
                      step={step}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      expectedArgs={expectedArgs}
                      showAdvancedSettings={showAdvancedSettings}
                      onToggleAdvancedSettings={() => setShowAdvancedSettings((v) => !v)}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    >
                      {argumentBindingsSection}
                    </ExternalCallStepSection>
                  );
                }

                if (step.type === "custom_code") {
                  return <CustomCodeSection step={step} onChange={onChange} />;
                }

                if (step.type === "push_to_client") {
                  return (
                    <PushToClientStepSection
                      step={step}
                      allNodes={allNodes}
                      allEdges={allEdges}
                      serviceNodeId={serviceNodeId}
                      endpoint={endpoint}
                      consumedEvent={consumedEvent}
                      expectedArgs={expectedArgs}
                      onChange={onChange}
                      onAutoMapArguments={handleAutoMapArguments}
                    >
                      {argumentBindingsSection}
                    </PushToClientStepSection>
                  );
                }

                if (step.type === "langgraph_invoke") {
                  return (
                    <LangGraphInvokeStepSection
                      step={step}
                      allNodes={allNodes}
                      onChange={onChange}
                    />
                  );
                }

                return (
                  <GenericFunctionRefSection step={step} onChange={onChange}>
                    {argumentBindingsSection}
                  </GenericFunctionRefSection>
                );
              })()}

              {/* Conditional Execution Guard (runIf) */}
              <div className="pt-2 border-t border-border/30 flex flex-col gap-2">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5">
                    <span className="text-[10px] font-semibold text-muted-foreground">
                      Execution Guard (runIf)
                    </span>
                    {step.runIf && (
                      <span className="px-1.5 py-0.2 rounded text-[9px] bg-amber-500/20 text-amber-300 font-mono">
                        Active
                      </span>
                    )}
                  </div>
                  <button
                    type="button"
                    className="text-[10px] text-primary/80 hover:text-primary font-medium transition-colors"
                    onClick={() => {
                      if (step.runIf) {
                        setShowRunIfGuard(false);
                        onChange({ ...step, runIf: undefined });
                      } else {
                        setShowRunIfGuard(true);
                        onChange({
                          ...step,
                          runIf: {
                            left: { kind: "req_body", field: "" },
                            operator: "truthy",
                          },
                        });
                      }
                    }}
                  >
                    {step.runIf ? "Remove guard" : "+ Add runIf condition"}
                  </button>
                </div>

                {showRunIfGuard && step.runIf && (
                  <div className="p-2 rounded-md bg-amber-500/5 border border-amber-500/20">
                    <span className="text-[9px] text-muted-foreground/80 block mb-1.5">
                      This step will execute only if the condition evaluates to true at runtime.
                    </span>
                    <ConditionExprEditor
                      expr={step.runIf}
                      availableSources={availableSources}
                      onChange={(runIf) => onChange({ ...step, runIf })}
                      compact={true}
                    />
                  </div>
                )}
              </div>

              {/* On Error Policy Section */}
              {step.type !== "return_response" && step.type !== "early_return" && (
                <StepOnErrorSection step={step} onChange={onChange} />
              )}

              {/* Enable / Disable Step */}
              <div className="flex items-center justify-between pt-1 border-t border-border/30">
                <span className="text-[9px] text-muted-foreground/50 font-mono">
                  {step.type !== "custom_code" && step.functionRef?.name
                    ? `const ${displayVarName} = await ${step.functionRef.name}(...)`
                    : `Step ${index + 1}`}
                </span>
                <button
                  type="button"
                  className={`flex items-center gap-1.5 text-[10px] transition-colors ${
                    step.enabled === false
                      ? "text-muted-foreground/50"
                      : "text-primary/70 hover:text-primary"
                  }`}
                  onClick={() =>
                    onChange({ ...step, enabled: step.enabled === false ? true : false })
                  }
                >
                  <Check size={11} />
                  {step.enabled === false ? "Enable step" : "Disable step"}
                </button>
              </div>
            </div>
          )}
        </div>
      )}
    </Draggable>
  );
};
